### Contract CREATE
POST  http://localhost:5000/v1/contract/create

### Contract UPDATE ALL
POST  http://localhost:5000/v1/contract/updates
Content-Type: application/json

{
    "user":"636fef4eabe49af17154aef3"
}

### Contract GET ALL ASC
GET http://localhost:5000/v1/contract

### Contract GET PAGE
GET http://localhost:5000/v1/contract?page=120

### Contract DELETE ALL
DELETE  http://localhost:5000/v1/contract/delete

### Contract SORT DESC
GET http://localhost:5000/v1/contract/group

### Contract DEBT
GET http://localhost:5000/v1/contract/debt

### find CONTRACT AND UPDATE
PATCH  http://localhost:5000/v1/contract/find
Content-Type: application/json

{
    "name":5,
    "status":false
}


### Contract PUPULATE
GET http://localhost:5000/v1/contract/populate