### User GET ALL
GET http://localhost:5000/v1/user

### User CREATE
POST  http://localhost:5000/v1/user/create
Content-Type: application/json

{
    "name":"Nguyễn Văn Công"
}

### User REGISTER
POST  http://localhost:5000/v1/user/register
Content-Type: application/json

{
    "username":"cong3",
    "password":"1",
    "fullname":"nguyen van cong 1",
    "phonenumber":"1111",
    "email":"NguyenCong@gmail.com",
    "role":"role1",
    "position":"Position",
    "imagepath":"img patch",
    "note":"Note 1"

}

### User LOGIN
POST  http://localhost:5000/v1/user/login
Content-Type: application/json

{
    "username":"cong1",
    "password":"1"
}

### User GET LISTS
GET http://localhost:5000/v1/user/getlists
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdhNTRlYTY2MGFjNjJhNGM1YjkxNGYiLCJpYXQiOjE2NjkwMTA3MzIsImV4cCI6MTY2OTAxNDMzMn0.ctJnW4h755Oek_xO0wJnHtl25SDp693xdSPJgZQip30
