### User GET ALL
GET http://localhost:5000/v1/user

### User CREATE
POST  http://localhost:5000/v1/user/create
Content-Type: application/json

{
    "name":"Nguyễn Văn Công"
}

### User REGISTER
POST  http://localhost:5000/v1/user/register
Content-Type: application/json

{
    "username":"cong4",
    "password":"1",
    "fullname":"nguyen van cong 1",
    "phonenumber":"1111",
    "email":"NguyenCong@gmail.com",
    "role":"role1",
    "position":"Position",
    "imagepath":"img patch",
    "note":"Note 1"

}

### User LOGIN
POST  http://localhost:5000/v1/user/login
Content-Type: application/json

{
    "username":"cong1",
    "password":"1"
}

### User GET LISTS
GET http://localhost:5000/v1/user/getlists
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdhNTRlYTY2MGFjNjJhNGM1YjkxNGYiLCJpYXQiOjE2NjkxMDgwNjgsImV4cCI6MTY2OTEwODA4OH0.F5-X3fcv7rFdqGJC1dTgHFs4MAiLAUb5rXqbx-et2dA


### User REFRESH-TOKEN
POST  http://localhost:5000/v1/user/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdhNTRlYTY2MGFjNjJhNGM1YjkxNGYiLCJpYXQiOjE2NjkwOTM2NTAsImV4cCI6MTY2OTA5NzI1MH0.Ho58hQVMZMqFbWKnR5Kypwg8Ext9JVX2oFF6ALsw0ZI"
}